import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/app/_components/Header";
import Footer from "@/app/_components/Footer";
import Sidebar from "@/app/_components/Sidebar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-full">
          <Sidebar />
          

          <div className="flex-1 flex flex-col">
            <Header />

            <main className="bg-[#080808]  p-12 overflow-y-auto  flex items-start justify-between text-white flex-1">
              {children}
            </main>
            <Footer/>
          </div>
        </div>
      </body>
    </html>
  );
}
