import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/app/_components/Header";
import Footer from "@/app/_components/Footer";
import Sidebar from "@/app/_components/Sidebar";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import Error from "./error";
import Loading from "./loading";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen">
          <Sidebar />

          <div className="flex-1">
            <Header />
            <ErrorBoundary fallback={<Error />}>
              <Suspense fallback={<Loading />}>
                <main className="bg-[#1D1D1D]  pt-16 overflow-y-auto h-full flex items-center text-white">
                  {children}
                </main>
              </Suspense>
            </ErrorBoundary>
          </div>
        </div>
      </body>
    </html>
  );
}
